<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <ApplicationIcon />
    <StartupObject />
    <PackageId>sistas.o2g-sdk</PackageId>
    <Authors>ALE International, SISTAS Sayisal Iletisim San.Tic. A.S.</Authors>
    <Description>This assembly is a SDK for OpenTouch Open Gateway API.
Unofficial fork of o2g-sdk with o2g 2.7.5 support.
See upstream at https://github.com/ALE-OPENNESS/CSharp-SDK</Description>
    <Copyright>Copyright © ALE International 2022</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>o2g.png</PackageIcon>
    <PackageIconUrl />
    <Version>2.7.5-sistas.1</Version>
    <AssemblyVersion>2.7.5.1</AssemblyVersion>
    <FileVersion>2.7.5.1</FileVersion>
    <PackageProjectUrl>https://github.com/SISTASOSS/CSharp-SDK/tree/2.7.4</PackageProjectUrl>
    <RepositoryUrl>https://github.com/SISTASOSS/CSharp-SDK/tree/2.7.4</RepositoryUrl>
    <PackageTags>o2g-sdk;fork; unofficial;sistas</PackageTags>
    <PackageReleaseNotes>This assembly is a SDK for OpenTouch Open Gateway API version 2.7.4.
Note that all APIs are not supported</PackageReleaseNotes>
    <Company>ALE International</Company>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DocumentationFile>.\o2g.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DocumentationFile>.\o2g-sdk.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="doc\**" />
    <EmbeddedResource Remove="doc\**" />
    <None Remove="doc\**" />
    <None Include="o2g.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Macross.Json.Extensions" Version="3.0.0" />
    <PackageReference Include="NLog" Version="5.5.0" />
    <PackageReference Include="NLog.Web.AspNetCore" Version="5.5.0" />
  </ItemGroup>

</Project>
