/*
* Copyright 2021 ALE International
*
* Permission is hereby granted, free of charge, to any person obtaining a copy of this 
* software and associated documentation files (the "Software"), to deal in the Software 
* without restriction, including without limitation the rights to use, copy, modify, merge, 
* publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons 
* to whom the Software is furnished to do so, subject to the following conditions:
* 
* The above copyright notice and this permission notice shall be included in all copies or 
* substantial portions of the Software.
* 
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING 
* BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND 
* NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, 
* DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
* OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace o2g.Types.CallCenterRsiNS
{
    /// <summary>
    /// <c>DataCollected</c> represents a collection of tones.
    /// DTMF tones are generated by parties on a call by pressing the dialpad digits 0 through 9 and * and # during the call.
    /// </summary>
    public class DataCollected
    {
        /// <summary>
        /// <c>CollectionCause</c> represents the reason why the digits collection ended.
        /// </summary>
        [JsonStringEnumMemberConverterOptions(deserializationFailureFallbackValue: CollectionCause.SfTerminated)]
        public enum CollectionCause
        {
            /// <summary>
            /// A specific tone specified in the retrieval criteria is received.
            /// </summary>
            [EnumMember(Value = "FLUSCHAR_RECEIVED")]
            FlushcharReceived,

            /// <summary>
            /// The number of tones specified in the retrieval criteria is received.
            /// </summary>
            [EnumMember(Value = "CHAR_COUNT_REACHED")]
            CharCountReached,

            /// <summary>
            /// The timeout specified in the retrieval criteria has elapsed.
            /// </summary>
            [EnumMember(Value = "TIMEOUT")]
            Timeout,

            /// <summary>
            /// An error occurs.
            /// </summary>
            [EnumMember(Value = "SF_TERMINATED")]
            SfTerminated
        }


        /// <summary>
        /// The collection digit identifier.
        /// </summary>
        /// <value>
        /// A <see langword="string"/> that represents the digits collection identifier.
        /// </value>
        public string CollCrid { get; init; }

        /// <summary>
        /// Return the collected digits.
        /// </summary>
        /// <value>
        /// A <see langword="string"/> that represents the collected digits".
        /// </value>
        public string Digits { get; init; }

        /// <summary>
        /// Return the cause of the digit collection termination.
        /// </summary>
        /// <value>
        /// A <see cref="CollectionCause"/> value that represents the reason of the digit collection termination.
        /// </value>
        public CollectionCause Cause { get; init; }
    }
}
